### ISSUE TITLE
Updater: Add ability to check for existence of (local) repository

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#1063]
For the purpose of supporting both tuf-enabled servers and legacy servers without additional configuration I'd like to be able to ask tuf.Updater "do you have local metadata for `<repository>`?". 

As a workaround I can check for existence of `<repositories_directory>/<repository>/metadata/current/root.json` but that feels like poking into tuf implementation details.

**Current behavior**:
```
>> updater = tuf.client.updater.Updater('non-existent', repository_mirrors)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jku/src/tuf/tuf/client/updater.py", line 740, in __init__
    raise tuf.exceptions.RepositoryError('Missing'
tuf.exceptions.RepositoryError: Missing './non-existent/metadata/current'.  This path must exist and, at a minimum, contain the Root metadata file.
```

This is very close to what I'd like -- the only issue is that RepositoryError is very generic, it's used for a lot of other things than Missing as well.

**Expected behavior**:
Maybe something like this

```
try:
    updater = tuf.client.updater.Updater('non-existent', repository_mirrors)
except MissingLocalRepositoryError:
    # we don't have root.json on device: use non-tuf-enabled code path


```

**Comment by jku** [comment]
relates to #967
