### ISSUE TITLE
metadata API: Improve exception handling in Metadata.sign()

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#2309]
Metadata.sign():
```python
        try:
            signature = signer.sign(bytes_data)
        except Exception as e:
            raise UnsignedMetadataError("Problem signing the metadata") from e
```

The reason we're catching Exception is that we have no idea what kind of errors might happen in Signer.sign() -- as an example, what does a Google Cloud Authentication error look like?

However, we do have to improve this somehow, maybe just leave generic exception handling to the application (which was the other approach we considered IIRC): this current approach leads to e.g. this:
* application signs with a HSMSigner, this leads to secret handler getting  called "Please enter PIN:"
* user decides they don't want to sign and presses ctrl-C
* application sees UnsignedMetadataError -- the logical assumption is a PIN input error so application tries signing again "Please enter PIN:"
* user is stuck without ability to exit without signing

I don't see reasonable ways to solve this within the application: Ctrl-C really should exit and not be a UnsignedMetadataError

**Comment by N-i-s-h-a-n-t** [comment]
I hope this will help.

try:
signature = signer.sign(bytes_data)
except AuthenticationError as e:
raise UnsignedMetadataError("Error signing metadata: authentication failed") from e
except SigningError as e:
raise UnsignedMetadataError("Error signing metadata: failed to sign data") from e
except HSMError as e:
raise UnsignedMetadataError("Error signing metadata: please check your HSM configuration") from e
except KeyboardInterrupt as e:
print("Signing process cancelled.")
 signature = None
except Exception as e:
raise UnsignedMetadataError("Error signing metadata: unknown error") from e

**Comment by DeshDeepakKant** [comment]
@jku I tried to reproduce it, but is showing this

```
 ~/python-tuf │ fix-metadata-sign-exception !1 ?6 ▓▒░ python examples/reproduce_hsm_issue.py                                                          ░▒▓ INT х │ python-tuf Py │ 12:26:35 AM 

Attempt 1 of 3

HSM requesting PIN...
Enter PIN (press Ctrl+C to cancel): ^C
PIN entry cancelled by user
Traceback (most recent call last):
  File "/home/desh/python-tuf/examples/reproduce_hsm_issue.py", line 69, in <module>
    main()
  File "/home/desh/python-tuf/examples/reproduce_hsm_issue.py", line 58, in main
    metadata.sign(signer)
  File "/home/desh/python-tuf/examples/reproduce_hsm_issue.py", line 42, in sign
    signature = signer.sign(b"test data")
  File "/home/desh/python-tuf/examples/reproduce_hsm_issue.py", line 32, in sign
    input("Enter PIN (press Ctrl+C to cancel): ")
KeyboardInterrupt

 ~/python-tuf │ fix-metadata-sign-exception !1 ?6 ▓▒░                                                                                                 ░▒▓ INT х │ python-tuf Py │ 12:27:30 AM 

```

is this issue still there?

**Comment by jku** [comment]
I would expect this to still happen... can you share your test app?

**Comment by DeshDeepakKant** [comment]
> I would expect this to still happen... can you share your test app?

```

from securesystemslib.signer import Signer
from unittest.mock import Mock
import time

class UnsignedMetadataError(Exception):
    """Simulate TUF's UnsignedMetadataError"""
    pass

class HSMSigner(Signer):
    """Simulates an HSM that requires PIN entry"""
    def __init__(self):
        self.keyid = "test_key_id"
    
    @classmethod
    def from_priv_key_uri(cls, privkey_uri: str) -> "HSMSigner":
        return cls()
    
    @property
    def public_key(self):
        mock_key = Mock()
        mock_key.keytype = "ed25519"
        mock_key.scheme = "ed25519"
        mock_key.keyid = self.keyid
        return mock_key
    
    def sign(self, data: bytes) -> bytes:
        """Simulate HSM PIN entry that can be interrupted"""
        print("\nHSM requesting PIN...")
        try:
            input("Enter PIN (press Ctrl+C to cancel): ")
            return b"dummy_signature"
        except KeyboardInterrupt:
            print("\nPIN entry cancelled by user")
            raise

def sign_with_retries(signer: Signer):
    """Simulate the actual application behavior with TUF"""
    try:
        return signer.sign(b"test data")
    except KeyboardInterrupt as e:
        # This is what TUF currently does - converts KeyboardInterrupt to UnsignedMetadataError
        raise UnsignedMetadataError(f"Failed to sign: User cancelled") from e

def main():
    signer = HSMSigner()
    max_attempts = 3
    attempt = 1
    
    while attempt <= max_attempts:
        print(f"\nAttempt {attempt} of {max_attempts}")
        try:
            sign_with_retries(signer)
            print("Signing successful!")
            break
        except UnsignedMetadataError as e:
            print(f"Signing failed: {type(e).__name__}: {str(e)}")
            if attempt < max_attempts:
                print("Retrying in 2 seconds...")
                time.sleep(2)
            attempt += 1

if __name__ == "__main__":
    main()

```

**Comment by jku** [comment]
That doesn't really reproduce the issue as it does not use Metadata.sign and doesn't try to do the same thing that Metadata.sign does (catching Exception and reraising as UnsignedMetadataError).

If you have a yubikey that does have a PIV key in it, something like this reproduces (and mocking Signer should work as well if you don't):

```
import os
from securesystemslib.signer import HSMSigner, Signer
from tuf.api.metadata import Root, Metadata

os.environ["PYKCS11LIB"] = "/usr/lib/x86_64-linux-gnu/libykcs11.so"

uri, key = HSMSigner.import_()
signer = Signer.from_priv_key_uri(uri, key, input)

md = Metadata(Root())
md.sign(signer)
# press ctrl-C here
```

That said, I just ran that and it does end up with `KeyboardInterrupt` getting printed (but not catchable, it just exits)... it looks like the important ingredient here is `input`: that stdlib function seems to have some special handling for KeyboardInterrupt. I originally used `click.prompt()` instead of input and with that you definitely get in that case is a UnsignedMetadataError being raised.

I don't really know what the right thing to do is at this point...

**Comment by jku** [comment]
```
        try:
            signature = signer.sign(bytes_data)
        except Exception as e:
            raise UnsignedMetadataError("Problem signing the metadata") from e
```

turns out `KeyboardInterrupt` is not an `Exception` -- so this works correctly in the normal `input()` case: we catch all "real" exceptions but not the keyboard interrupt: that is allowed to raise as is.

So I suppose the real issue here was that click.prompt() raises `click.exceptions.Abort` (which is a type of `Exception`) instead of `KeyboardInterrupt` (which isn't) .  So maybe not a bug in python-tuf?

**Comment by jku** [comment]
I'm going to close on the assumption that this still works with normal KeyboardInterrupt: Handling Exception is not great but we don't really have better ideas
