### ISSUE TITLE
failure in with-sslib-main tests after recent securesystemslib refactoring

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf#2444]
This likely relates to recent securesystemslib signer refactoring. _with-sslib-master_ fails at the moment: https://github.com/theupdateframework/python-tuf/actions/runs/5855914808/job/15874647606

```
2023-08-14T12:51:58.8613186Z ======================================================================
2023-08-14T12:51:58.8613833Z ERROR: test_sign_failures (test_api.TestMetadata.test_sign_failures)
2023-08-14T12:51:58.8653159Z ----------------------------------------------------------------------
2023-08-14T12:51:58.8654114Z Traceback (most recent call last):
2023-08-14T12:51:58.8676710Z   File "/home/runner/work/python-tuf/python-tuf/tests/test_api.py", line 244, in test_sign_failures
2023-08-14T12:51:58.8677195Z     sslib_signer = SSlibSigner(key_dict)
2023-08-14T12:51:58.8677485Z                    ^^^^^^^^^^^^^^^^^^^^^
2023-08-14T12:51:58.8678275Z   File "/home/runner/work/python-tuf/python-tuf/.tox/with-sslib-main/lib/python3.11/site-packages/securesystemslib/signer/_sslib_signer.py", line 50, in __init__
2023-08-14T12:51:58.8679295Z     self._crypto_signer = CryptoSigner.from_securesystemslib_key(key_dict)
2023-08-14T12:51:58.8679675Z                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-14T12:51:58.8680520Z   File "/home/runner/work/python-tuf/python-tuf/.tox/with-sslib-main/lib/python3.11/site-packages/securesystemslib/signer/_crypto_signer.py", line 79, in from_securesystemslib_key
2023-08-14T12:51:58.8681716Z     load_pem_private_key(private.encode(), ***
2023-08-14T12:51:58.8682042Z     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-14T12:51:58.8682817Z   File "/home/runner/work/python-tuf/python-tuf/.tox/with-sslib-main/lib/python3.11/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 25, in load_pem_private_key
2023-08-14T12:51:58.8683349Z     return ossl.load_pem_private_key(
2023-08-14T12:51:58.8683624Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-08-14T12:51:58.8684348Z   File "/home/runner/work/python-tuf/python-tuf/.tox/with-sslib-main/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 747, in load_pem_private_key
2023-08-14T12:51:58.8684828Z     return self._load_key(
2023-08-14T12:51:58.8685089Z            ^^^^^^^^^^^^^^^
2023-08-14T12:51:58.8685769Z   File "/home/runner/work/python-tuf/python-tuf/.tox/with-sslib-main/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 929, in _load_key
2023-08-14T12:51:58.8686248Z     self._handle_key_loading_error()
2023-08-14T12:51:58.8686991Z   File "/home/runner/work/python-tuf/python-tuf/.tox/with-sslib-main/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 984, in _handle_key_loading_error
2023-08-14T12:51:58.8687470Z     raise ValueError(
2023-08-14T12:51:58.8688484Z ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [<OpenSSLError(code=503841036, lib=60, reason=524556, reason_text=unsupported)>])
2023-08-14T12:51:58.8689018Z 
```

**Comment by jku** [comment]
I guess this is a reasonable way to fail? the key is clearly incorrect (and the SSlibSigner constructor is already documented to not be the correct way to use the API)

So we could just change the test?
