### ISSUE TITLE
Incorrect repo instructions re. optional args in repository_tool key functions

### ISSUE THREAD

**Issue by awwad** [theupdateframework/tuf#591]
Some of the [TUF repository instructions](https://github.com/theupdateframework/tuf/blob/develop/tuf/README.md#how-to-create-and-modify-a-tuf-repository) are no longer accurate. (This may be accidental or intentional in these cases, but either the instructions should be updated or the code should be adjusted so that the instructions still work.)

## bits and password are no longer optional arguments when creating a key

Those args seem to no longer be optional.

What the instructions say:
```
# If the key length is unspecified, it defaults to 3072 bits. A length of less
# than 2048 bits raises an exception. A password may be supplied as an
# argument, otherwise a user prompt is presented.
>>> generate_and_write_rsa_keypair("keystore/root_key2")
Enter a password for the RSA key:
Confirm:
```

What actually happens:
```
>>> generate_and_write_rsa_keypair("keystore/root_key2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: generate_and_write_rsa_keypair() missing 2 required positional arguments: 'bits' and 'password'
```

## password is no longer optional when loading a private key

What the instructions say:
```# Import an existing private key.  Importing a private key requires a password,
# whereas importing a public key does not.
>>> private_root_key = import_rsa_privatekey_from_file("keystore/root_key")
Enter a password for the encrypted RSA key:
```
What actually happens:
```
>>> private_root_key = import_rsa_privatekey_from_file("keystore/root_key")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: import_rsa_privatekey_from_file() missing 1 required positional argument: 'password'
```

## Likewise for ed25519: password is no longer optional when creating or loading a private key

What the instructions say:
```
# Generate and write an Ed25519 key pair.  The private key is saved encrypted.
# A 'password' argument may be supplied, otherwise a prompt is presented.
>>> generate_and_write_ed25519_keypair('keystore/ed25519_key')
Enter a password for the Ed25519 key:
Confirm:
>>> private_ed25519_key = import_ed25519_privatekey_from_file('keystore/ed25519_key')
Enter a password for the encrypted Ed25519 key:
```

What actually happens:
```
>>> generate_and_write_ed25519_keypair('keystore/ed25519_key')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: generate_and_write_ed25519_keypair() missing 1 required positional argument: 'password'
>>> private_ed25519_key = import_ed25519_privatekey_from_file('keystore/ed25519_key')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: import_ed25519_privatekey_from_file() missing 1 required positional argument: 'password'
```

## The first issue in this listing persists through the rest of the document for RSA key creation and loading:

e.g.

What the instructions say:
```
# Generate keys for the remaining top-level roles.  The root keys have been set above.
# The password argument may be omitted if a password prompt is needed.
>>> generate_and_write_rsa_keypair("keystore/targets_key", password="password")
>>> generate_and_write_rsa_keypair("keystore/snapshot_key", password="password")
>>> generate_and_write_rsa_keypair("keystore/timestamp_key", password="password")
```

What actually happens:
(Each of these fails because bits is missing.)
```
>>> generate_and_write_rsa_keypair("keystore/targets_key", password="password")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: generate_and_write_rsa_keypair() missing 1 required positional argument: 'bits'
```

**Comment by vladimir-v-diaz** [comment]
This issue is fixed in https://github.com/theupdateframework/tuf/pull/582.
