### ISSUE TITLE
Failed to Add Target Files when following instruction in TUTORIAL.md

### ISSUE THREAD

**Issue by thangld322** [theupdateframework/tuf#772]
I was following the [TUTORIAL.md ](https://github.com/theupdateframework/tuf/blob/develop/docs/TUTORIAL.md)
And at the line `private_targets_key = import_rsa_privatekey_from_file("keystore/targets_key")`
after I enter password, it returns an error: 

_Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/securesystemslib/pyca_crypto_keys.py", line 611, in create_rsa_public_and_private_from_pem
    passphrase, backend=default_backend())
  File "/usr/local/lib/python3.6/dist-packages/cryptography/hazmat/primitives/serialization.py", line 20, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/usr/local/lib/python3.6/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1014, in load_pem_private_key
    password,
  File "/usr/local/lib/python3.6/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1233, in _load_key
    self._handle_key_loading_error()
  File "/usr/local/lib/python3.6/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1291, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thangld_anm/newSIEM/tuf/tuf/repository_lib.py", line 824, in import_rsa_privatekey_from_file
    filepath, password)
  File "/usr/local/lib/python3.6/dist-packages/securesystemslib/interface.py", line 350, in import_rsa_privatekey_from_file
    scheme, password)
  File "/usr/local/lib/python3.6/dist-packages/securesystemslib/keys.py", line 974, in import_rsakey_from_private_pem
    pem, password)
  File "/usr/local/lib/python3.6/dist-packages/securesystemslib/pyca_crypto_keys.py", line 625, in create_rsa_public_and_private_from_pem
    ' cannot be generated from the encrypted PEM string: ' + str(e))
securesystemslib.exceptions.CryptoError: RSA (public, private) tuple cannot be generated from the encrypted PEM string: Could not deserialize key data.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/securesystemslib/pyca_crypto_keys.py", line 611, in create_rsa_public_and_private_from_pem
    passphrase, backend=default_backend())
  File "/usr/local/lib/python3.6/dist-packages/cryptography/hazmat/primitives/serialization.py", line 20, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/usr/local/lib/python3.6/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1014, in load_pem_private_key
    password,
  File "/usr/local/lib/python3.6/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1233, in _load_key
    self._handle_key_loading_error()
  File "/usr/local/lib/python3.6/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 1291, in _handle_key_loading_error
    raise ValueError("Could not deserialize key data.")
ValueError: Could not deserialize key data.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thangld_anm/newSIEM/tuf/tuf/repository_tool.py", line 3185, in import_rsa_privatekey_from_file
    return repo_lib.import_rsa_privatekey_from_file(filepath, password)
  File "/home/thangld_anm/newSIEM/tuf/tuf/repository_lib.py", line 831, in import_rsa_privatekey_from_file
    filepath, password, prompt=True)
  File "/usr/local/lib/python3.6/dist-packages/securesystemslib/interface.py", line 350, in import_rsa_privatekey_from_file
    scheme, password)
  File "/usr/local/lib/python3.6/dist-packages/securesystemslib/keys.py", line 974, in import_rsakey_from_private_pem
    pem, password)
  File "/usr/local/lib/python3.6/dist-packages/securesystemslib/pyca_crypto_keys.py", line 625, in create_rsa_public_and_private_from_pem
    ' cannot be generated from the encrypted PEM string: ' + str(e))
securesystemslib.exceptions.CryptoError: RSA (public, private) tuple cannot be generated from the encrypted PEM string: Could not deserialize key data.
_
Can you tell me how can I fix this? Thank you.

**Comment by awwad** [comment]
I'll take a look and see if I can reproduce this today. 🙂 Thanks for creating an issue.

**Comment by thangld322** [comment]
@awwad thanks for replying.
Seem like the TUTORIAL is too old and does not work for the current version.
Please help, I can't find a complete guide to use this framework..

**Comment by awwad** [comment]
When following tutorial instructions, `repository.get_filepaths_in_directory()` returns filepaths of the form `'repository/targets/file1.txt'` (i.e. relative to current working directory), and `repository.add_targets()` is expecting filepaths of the form `'file1.txt'` (relative to the root Targets directory, regardless of current working directory).

It seems likely that at some point, the expectations here diverged. I'll fix the tutorial shortly. I've also written some regression testing and will make that pull request so that future changes that break the tutorial are detected in automated testing.

Meanwhile, you can easily adjust the file paths you enter. Thanks a bunch for the report!

**Comment by awwad** [comment]
I can't seem to reproduce this specific issue. Those lines in the tutorial seem to work fine for me. Can you tell me a bit about your environment?

I do see later lines in the tutorial that break, though, so thanks very much for the report.

For example, when following tutorial instructions, `repository.get_filepaths_in_directory()` returns filepaths of the form `'repository/targets/file1.txt'` (i.e. relative to current working directory), and `repository.add_targets()` is expecting filepaths of the form `'file1.txt'` (relative to the root Targets directory, regardless of current working directory).

It seems likely that at some point, the expectations here diverged.

**More to the point,** I've written some regression testing and will make that pull request soon so that future changes that break the tutorial are detected in automated testing, on several environments.

**Comment by awwad** [comment]
I'm updating the tutorial to fix some issues with it, in this PR: https://github.com/theupdateframework/tuf/pull/775

(Again, though, I didn't encounter the RSA key import error you mentioned above, so if you still experience that, I could use some more info on the environment in which you're running.)

**Comment by thangld322** [comment]
Thanks for quick response :+1: 
Sorry I didn't make it detail enough.
1. I run it on ubuntu 16.04.5 with python 3.6.6. I just realize the tutorial is for python 2
2. The line `import_rsa_privatekey_from_file` after create_repo works fine but that same line after load_repo encounters the error I mentioned.

**Comment by thangld322** [comment]
I test again with python 2.7.7
After run the lines after create_repo successfully, I have this
.
├── client
│   └── tufclient
│       └── metadata
│           ├── current
│           │   ├── 1.root.json
│           │   ├── role1.json
│           │   ├── role2.json
│           │   ├── root.json
│           │   ├── snapshot.json
│           │   ├── targets.json
│           │   └── timestamp.json
│           └── previous
│               ├── 1.root.json
│               ├── role1.json
│               ├── role2.json
│               ├── root.json
│               ├── snapshot.json
│               ├── targets.json
│               └── timestamp.json
├── delegation_key
├── delegation_key.pub
├── gen.py
├── load.py
├── repository
│   ├── metadata
│   │   ├── 1.root.json
│   │   ├── role1.json
│   │   ├── role2.json
│   │   ├── root.json
│   │   ├── snapshot.json
│   │   ├── targets.json
│   │   └── timestamp.json
│   ├── metadata.staged
│   │   ├── 1.root.json
│   │   ├── role1.json
│   │   ├── role2.json
│   │   ├── root.json
│   │   ├── snapshot.json
│   │   ├── targets.json
│   │   └── timestamp.json
│   └── targets
│       ├── file1.txt
│       ├── file2.txt
│       ├── file3.txt
│       └── myproject
│           └── file4.txt
├── root_key
├── root_key.pub
├── snapshot_key
├── snapshot_key.pub
├── targets_key
├── targets_key.pub
├── timestamp_key
└── timestamp_key.pub

10 directories, 44 files
##################################################
Then I run the lines after load_repo:
`from tuf.repository_tool import *
import os

repository = load_repository('repository/', 'repository')
list_of_targets = repository.get_filepaths_in_directory("repository/targets/",
                                                        recursive_walk=False, followlinks=True)
print(list_of_targets)
list_of_targets_shorts = ['file2.txt', 'file1.txt', 'file3.txt']
repository.targets.add_targets(list_of_targets_shorts)

target4_filepath = "repository/targets/myproject/file4.txt"
target4_filepath_shorts = "myproject/file4.txt"
octal_file_permissions = oct(os.stat(target4_filepath).st_mode)[4:]
custom_file_permissions = {'file_permissions': octal_file_permissions}
repository.targets.add_target(target4_filepath_shorts, custom_file_permissions)

private_targets_key = import_rsa_privatekey_from_file("targets_key")
repository.targets.load_signing_key(private_targets_key)
private_snapshot_key = import_rsa_privatekey_from_file("snapshot_key")
repository.snapshot.load_signing_key(private_snapshot_key)
private_timestamp_key = import_rsa_privatekey_from_file("timestamp_key")
repository.timestamp.load_signing_key(private_timestamp_key)

print(repository.dirty_roles())
repository.writeall()`

`python load.py`
***ERROR:
`['repository/targets/file3.txt', 'repository/targets/file1.txt', 'repository/targets/file2.txt']
Traceback (most recent call last):
  File "load.py", line 17, in <module>
    private_targets_key = import_rsa_privatekey_from_file("targets_key")
  File "/usr/local/lib/python2.7/dist-packages/tuf/repository_tool.py", line 3185, in import_rsa_privatekey_from_file
    return repo_lib.import_rsa_privatekey_from_file(filepath, password)
  File "/usr/local/lib/python2.7/dist-packages/tuf/repository_lib.py", line 819, in import_rsa_privatekey_from_file
    filepath, password)
  File "/usr/local/lib/python2.7/dist-packages/securesystemslib/interface.py", line 350, in import_rsa_privatekey_from_file
    scheme, password)
  File "/usr/local/lib/python2.7/dist-packages/securesystemslib/keys.py", line 974, in import_rsakey_from_private_pem
    pem, password)
  File "/usr/local/lib/python2.7/dist-packages/securesystemslib/pyca_crypto_keys.py", line 625, in create_rsa_public_and_private_from_pem
    ' cannot be generated from the encrypted PEM string: ' + str(e))
securesystemslib.exceptions.CryptoError: RSA (public, private) tuple cannot be generated from the encrypted PEM string: Could not deserialize key data.
`

**Comment by awwad** [comment]
The tutorial should work in both Python2 and Python3.
If you check out the PR #775 branch, cd into the tests/ directory, and run `python test_tutorial.py`, what happens?

**Comment by thangld322** [comment]
The test runs successfully.
Look like my code is wrong somewhere. I'll take a look.
Thanks for response. You can close this issue now. :+1:
